server:
  port: ${SERVER_PORT:8080}

spring:
  profiles:
    active:
      - ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: sisimpur-library
  datasource:
    url: jdbc:postgresql://localhost:5433/sisimpur?stringtype=unspecified
    username: halum
    password: machvaja
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        '[format_sql]': true
    show-sql: true