server:
  port: 8080

spring:
  application:
    name: sisimpur-library
  datasource:
    url: jdbc:postgresql://localhost:5432/sisimpur?stringtype=unspecified
    username: halum
    password: machvaja
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      validation-timeout: 5000
      leak-detection-threshold: 60000
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
    show-sql: false

jwt:
  secret: sisimpur_library_secret_key_that_should_be_long_enough_for_production
  expirationMs: 1800000

logging:
  level:
    com.sisimpur.library: INFO
    org.springframework.security: WARN
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
